<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OportunidadCmr', 'doctrine');

/**
 * BaseOportunidadCmr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_opor_cmr
 * @property string $sku
 * @property integer $precio_internet
 * @property integer $precio_cmr
 * @property timestamp $fecha_vigencia
 * 
 * @method integer        getIdOporCmr()       Returns the current record's "id_opor_cmr" value
 * @method string         getSku()             Returns the current record's "sku" value
 * @method integer        getPrecioInternet()  Returns the current record's "precio_internet" value
 * @method integer        getPrecioCmr()       Returns the current record's "precio_cmr" value
 * @method timestamp      getFechaVigencia()   Returns the current record's "fecha_vigencia" value
 * @method OportunidadCmr setIdOporCmr()       Sets the current record's "id_opor_cmr" value
 * @method OportunidadCmr setSku()             Sets the current record's "sku" value
 * @method OportunidadCmr setPrecioInternet()  Sets the current record's "precio_internet" value
 * @method OportunidadCmr setPrecioCmr()       Sets the current record's "precio_cmr" value
 * @method OportunidadCmr setFechaVigencia()   Sets the current record's "fecha_vigencia" value
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOportunidadCmr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oportunidad_cmr');
        $this->hasColumn('id_opor_cmr', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('sku', 'string', 7, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('precio_internet', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('precio_cmr', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_vigencia', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}