<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServiciosPorTienda', 'doctrine');

/**
 * BaseServiciosPorTienda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tienda
 * @property integer $id_servicio_tienda
 * 
 * @method integer            getIdTienda()           Returns the current record's "id_tienda" value
 * @method integer            getIdServicioTienda()   Returns the current record's "id_servicio_tienda" value
 * @method ServiciosPorTienda setIdTienda()           Sets the current record's "id_tienda" value
 * @method ServiciosPorTienda setIdServicioTienda()   Sets the current record's "id_servicio_tienda" value
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiciosPorTienda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicios_por_tienda');
        $this->hasColumn('id_tienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_servicio_tienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}