<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pais', 'doctrine');

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pais
 * @property string $desc_pais
 * @property string $sigla
 * @property Doctrine_Collection $EncuestaPreguntas
 * @property Doctrine_Collection $Endpoint
 * @property Doctrine_Collection $Region
 * @property Doctrine_Collection $Tienda
 * 
 * @method integer             getIdPais()            Returns the current record's "id_pais" value
 * @method string              getDescPais()          Returns the current record's "desc_pais" value
 * @method string              getSigla()             Returns the current record's "sigla" value
 * @method Doctrine_Collection getEncuestaPreguntas() Returns the current record's "EncuestaPreguntas" collection
 * @method Doctrine_Collection getEndpoint()          Returns the current record's "Endpoint" collection
 * @method Doctrine_Collection getRegion()            Returns the current record's "Region" collection
 * @method Doctrine_Collection getTienda()            Returns the current record's "Tienda" collection
 * @method Pais                setIdPais()            Sets the current record's "id_pais" value
 * @method Pais                setDescPais()          Sets the current record's "desc_pais" value
 * @method Pais                setSigla()             Sets the current record's "sigla" value
 * @method Pais                setEncuestaPreguntas() Sets the current record's "EncuestaPreguntas" collection
 * @method Pais                setEndpoint()          Sets the current record's "Endpoint" collection
 * @method Pais                setRegion()            Sets the current record's "Region" collection
 * @method Pais                setTienda()            Sets the current record's "Tienda" collection
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('desc_pais', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('sigla', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EncuestaPreguntas', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasMany('Endpoint', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasMany('Region', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasMany('Tienda', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));
    }
}