<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FuncionPais', 'doctrine');

/**
 * BaseFuncionPais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_funcion
 * @property integer $id_pais
 * @property Funcion $funcion
 * @property Pais $pais
 * 
 * @method integer     getIdFuncion()  Returns the current record's "id_funcion" value
 * @method integer     getIdPais()     Returns the current record's "id_pais" value
 * @method Funcion     getFuncion()    Returns the current record's "funcion" value
 * @method Pais        getPais()       Returns the current record's "pais" value
 * @method FuncionPais setIdFuncion()  Sets the current record's "id_funcion" value
 * @method FuncionPais setIdPais()     Sets the current record's "id_pais" value
 * @method FuncionPais setFuncion()    Sets the current record's "funcion" value
 * @method FuncionPais setPais()       Sets the current record's "pais" value
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionPais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcion_pais');
        $this->hasColumn('id_funcion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('funcion_pais_index', array(
             'fields' => 
             array(
              0 => 'id_funcion',
              1 => 'id_pais',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Funcion as funcion', array(
             'local' => 'id_funcion',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Pais as pais', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais',
             'onDelete' => 'CASCADE'));
    }
}