<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPregunta', 'doctrine');

/**
 * BaseTipoPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_preg
 * @property string $desc_tipo_preg
 * @property Doctrine_Collection $EncuestaPreguntas
 * 
 * @method integer             getIdTipoPreg()        Returns the current record's "id_tipo_preg" value
 * @method string              getDescTipoPreg()      Returns the current record's "desc_tipo_preg" value
 * @method Doctrine_Collection getEncuestaPreguntas() Returns the current record's "EncuestaPreguntas" collection
 * @method TipoPregunta        setIdTipoPreg()        Sets the current record's "id_tipo_preg" value
 * @method TipoPregunta        setDescTipoPreg()      Sets the current record's "desc_tipo_preg" value
 * @method TipoPregunta        setEncuestaPreguntas() Sets the current record's "EncuestaPreguntas" collection
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pregunta');
        $this->hasColumn('id_tipo_preg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('desc_tipo_preg', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EncuestaPreguntas', array(
             'local' => 'id_tipo_preg',
             'foreign' => 'id_tipo_preg',
             'onDelete' => 'SET NULL'));
    }
}