<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OportunidadCmr', 'doctrine');

/**
 * BaseOportunidadCmr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_opor_cmr
 * @property string $sku
 * @property string $nombre_producto
 * @property integer $precio_internet
 * @property string $unidad_med_int
 * @property integer $precio_cmr
 * @property string $unidad_med_cmr
 * @property timestamp $fecha_vig_des
 * @property timestamp $fecha_vig_has
 * @property integer $id_pais
 * @property Pais $Pais
 * 
 * @method integer        getIdOporCmr()       Returns the current record's "id_opor_cmr" value
 * @method string         getSku()             Returns the current record's "sku" value
 * @method string         getNombreProducto()  Returns the current record's "nombre_producto" value
 * @method integer        getPrecioInternet()  Returns the current record's "precio_internet" value
 * @method string         getUnidadMedInt()    Returns the current record's "unidad_med_int" value
 * @method integer        getPrecioCmr()       Returns the current record's "precio_cmr" value
 * @method string         getUnidadMedCmr()    Returns the current record's "unidad_med_cmr" value
 * @method timestamp      getFechaVigDes()     Returns the current record's "fecha_vig_des" value
 * @method timestamp      getFechaVigHas()     Returns the current record's "fecha_vig_has" value
 * @method integer        getIdPais()          Returns the current record's "id_pais" value
 * @method Pais           getPais()            Returns the current record's "Pais" value
 * @method OportunidadCmr setIdOporCmr()       Sets the current record's "id_opor_cmr" value
 * @method OportunidadCmr setSku()             Sets the current record's "sku" value
 * @method OportunidadCmr setNombreProducto()  Sets the current record's "nombre_producto" value
 * @method OportunidadCmr setPrecioInternet()  Sets the current record's "precio_internet" value
 * @method OportunidadCmr setUnidadMedInt()    Sets the current record's "unidad_med_int" value
 * @method OportunidadCmr setPrecioCmr()       Sets the current record's "precio_cmr" value
 * @method OportunidadCmr setUnidadMedCmr()    Sets the current record's "unidad_med_cmr" value
 * @method OportunidadCmr setFechaVigDes()     Sets the current record's "fecha_vig_des" value
 * @method OportunidadCmr setFechaVigHas()     Sets the current record's "fecha_vig_has" value
 * @method OportunidadCmr setIdPais()          Sets the current record's "id_pais" value
 * @method OportunidadCmr setPais()            Sets the current record's "Pais" value
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOportunidadCmr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oportunidad_cmr');
        $this->hasColumn('id_opor_cmr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sku', 'string', 7, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('nombre_producto', 'string', 200, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('precio_internet', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('unidad_med_int', 'string', 10, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('precio_cmr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidad_med_cmr', 'string', 10, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('fecha_vig_des', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_vig_has', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pais', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));
    }
}