<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EncuestaPreguntas', 'doctrine');

/**
 * BaseEncuestaPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_enc_preg
 * @property integer $id_tipo_preg
 * @property string $valor_defecto
 * @property string $desc_pregunta
 * @property string $estado
 * @property integer $id_pais
 * @property Pais $Pais
 * @property TipoPregunta $TipoPregunta
 * @property Doctrine_Collection $EncuestaRespuestas
 * 
 * @method integer             getIdEncPreg()          Returns the current record's "id_enc_preg" value
 * @method integer             getIdTipoPreg()         Returns the current record's "id_tipo_preg" value
 * @method string              getValorDefecto()       Returns the current record's "valor_defecto" value
 * @method string              getDescPregunta()       Returns the current record's "desc_pregunta" value
 * @method string              getEstado()             Returns the current record's "estado" value
 * @method integer             getIdPais()             Returns the current record's "id_pais" value
 * @method Pais                getPais()               Returns the current record's "Pais" value
 * @method TipoPregunta        getTipoPregunta()       Returns the current record's "TipoPregunta" value
 * @method Doctrine_Collection getEncuestaRespuestas() Returns the current record's "EncuestaRespuestas" collection
 * @method EncuestaPreguntas   setIdEncPreg()          Sets the current record's "id_enc_preg" value
 * @method EncuestaPreguntas   setIdTipoPreg()         Sets the current record's "id_tipo_preg" value
 * @method EncuestaPreguntas   setValorDefecto()       Sets the current record's "valor_defecto" value
 * @method EncuestaPreguntas   setDescPregunta()       Sets the current record's "desc_pregunta" value
 * @method EncuestaPreguntas   setEstado()             Sets the current record's "estado" value
 * @method EncuestaPreguntas   setIdPais()             Sets the current record's "id_pais" value
 * @method EncuestaPreguntas   setPais()               Sets the current record's "Pais" value
 * @method EncuestaPreguntas   setTipoPregunta()       Sets the current record's "TipoPregunta" value
 * @method EncuestaPreguntas   setEncuestaRespuestas() Sets the current record's "EncuestaRespuestas" collection
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEncuestaPreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuesta_preguntas');
        $this->hasColumn('id_enc_preg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_preg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valor_defecto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('desc_pregunta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'ACT',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pais', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais'));

        $this->hasOne('TipoPregunta', array(
             'local' => 'id_tipo_preg',
             'foreign' => 'id_tipo_preg'));

        $this->hasMany('EncuestaRespuestas', array(
             'local' => 'id_enc_preg',
             'foreign' => 'id_enc_preg'));
    }
}