<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AppPais', 'doctrine');

/**
 * BaseAppPais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_aplicacion
 * @property integer $id_pais
 * @property Aplicacion $aplicacion
 * @property Pais $pais
 * 
 * @method integer    getIdAplicacion()  Returns the current record's "id_aplicacion" value
 * @method integer    getIdPais()        Returns the current record's "id_pais" value
 * @method Aplicacion getAplicacion()    Returns the current record's "aplicacion" value
 * @method Pais       getPais()          Returns the current record's "pais" value
 * @method AppPais    setIdAplicacion()  Sets the current record's "id_aplicacion" value
 * @method AppPais    setIdPais()        Sets the current record's "id_pais" value
 * @method AppPais    setAplicacion()    Sets the current record's "aplicacion" value
 * @method AppPais    setPais()          Sets the current record's "pais" value
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppPais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_pais');
        $this->hasColumn('id_aplicacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_pais', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('app_pais_index', array(
             'fields' => 
             array(
              0 => 'id_aplicacion',
              1 => 'id_pais',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aplicacion as aplicacion', array(
             'local' => 'id_aplicacion',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Pais as pais', array(
             'local' => 'id_pais',
             'foreign' => 'id_pais',
             'onDelete' => 'CASCADE'));
    }
}