<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/24 16:16:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sodimac',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
