<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/25 15:07:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mant_app_sodimac',
  'username' => 'sodimac',
  'password' => 'sodimac',
  'name' => 'doctrine',
)),);
