<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/24 23:11:07
sfConfig::add(array(
  'mod_oportunidadcmr_enabled' => true,
  'mod_oportunidadcmr_view_class' => 'sfPHP',
));
