<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/25 09:54:26
sfConfig::add(array(
  'mod_oportunidadcmr_enabled' => true,
  'mod_oportunidadcmr_view_class' => 'sfPHP',
));
