# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing



delete_oportunidad:
  url: /admin/OportunidadCMR/:id_opor_cmr/delete
  class: sfDoctrineRoute
  params: { module: OportunidadCMR, action: delete }
  options: { model: OportunidadCmr, type: object }
  requirements:
    sf_method: DELETE
    id_opor_cmr: \d+

delete_pregunta:
  url: /admin/Preguntas/:id_enc_preg/delete
  class: sfDoctrineRoute
  params: { module: Preguntas, action: delete }
  options: { model: EncuestaPreguntas, type: object }
  requirements:
    sf_method: DELETE
    id_enc_preg: \d+

delete_tipo_pregunta:
  url: /admin/TipoPregunta/:id_tipo_preg/delete
  class: sfDoctrineRoute
  params: { module: TipoPregunta, action: delete }
  options: { model: TipoPregunta, type: object }
  requirements:
    sf_method: DELETE
    id_tipo_preg: \d+

delete_cabecera_respuestas:
  url: /admin/CabeceraRespuestas/:id_enc_cab_resp/delete
  class: sfDoctrineRoute
  params: { module: CabeceraRespuestas, action: delete }
  options: { model: EncuestaCabeceraRespuestas, type: object }
  requirements:
    sf_method: DELETE
    id_enc_cab_resp: \d+

delete_respuestas:
  url: /admin/Respuestas/:id_enc_resp/delete
  class: sfDoctrineRoute
  params: { module: Respuestas, action: delete }
  options: { model: EncuestaRespuestas, type: object }
  requirements:
    sf_method: DELETE
    id_enc_resp: \d+

delete_tienda:
  url: /admin/Tiendas/:id_tienda/delete
  class: sfDoctrineRoute
  params: { module: Tiendas, action: delete }
  options: { model: Tienda, type: object }
  requirements:
    sf_method: DELETE
    id_tienda: \d+

delete_tienda_servicio:
  url: /admin/Tiendas/:id/delete/Servicio/:idServicio
  class: sfDoctrineRoute
  params: { module: Tiendas, action: deleteServicio }
  options: { model: ServiciosPorTienda, type: object }
  requirements:
    sf_method: DELETE
    id: \d+
    idServicio: \d+

delete_tipo_tienda:
  url: /admin/TipoTienda/:id_tipo_tienda/delete
  class: sfDoctrineRoute
  params: { module: TipoTienda, action: delete }
  options: { model: TipoTienda, type: object }
  requirements:
    sf_method: DELETE
    id_tipo_tienda: \d+

delete_servicio:
  url: /admin/Servicios/:id_servicio_tienda/delete
  class: sfDoctrineRoute
  params: { module: Servicios, action: delete }
  options: { model: ServiciosTienda, type: object }
  requirements:
    sf_method: DELETE
    id_servicio_tienda: \d+

delete_endpoint:
  url: /admin/Endpoint/:id_endpoint/delete
  class: sfDoctrineRoute
  params: { module: Endpoint, action: delete }
  options: { model: Endpoint, type: object }
  requirements:
    sf_method: DELETE
    id_endpoint: \d+

delete_aplicacion:
  url: /admin/Aplicacion/:id/delete
  class: sfDoctrineRoute
  params: { module: Aplicacion, action: delete }
  options: { model: Aplicacion, type: object }
  requirements:
    sf_method: DELETE
    id: \d+

delete_aplicacion_pais:
  url: /admin/Aplicacion/:idApp/delete/Pais/:idPais
  class: sfDoctrineRoute
  params: { module: Aplicacion, action: deletePais }
  options: { model: AplicacionPais, type: object }
  requirements:
    sf_method: DELETE
    idApp: \d+
    idPais: \d+

delete_funcion_pais:
  url: /admin/Funcion/:idFunc/delete/Pais/:idPais
  class: sfDoctrineRoute
  params: { module: Funcion, action: deletePais }
  options: { model: FuncionPais, type: object }
  requirements:
    sf_method: DELETE
    idFunc: \d+
    idPais: \d+

# default rules
homepage:
  url:   /admin/
  param: { module: OportunidadCMR, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /admin/:module
  param: { action: index }

default:
  url:   /admin/:module/:action/*
