<?php

/**
 * AplicacionPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AplicacionPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AplicacionPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AplicacionPais');
    }
}