<?php

/**
 * AplicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AplicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AplicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aplicacion');
    }
}