<?php

/**
 * AppPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppPais');
    }
}