<?php

/**
 * EncuestaPreguntasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EncuestaPreguntasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EncuestaPreguntasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EncuestaPreguntas');
    }
}