<?php

/**
 * EncuestaPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EncuestaPreguntas extends BaseEncuestaPreguntas
{
	public function __toString()
	{
		return $this->getDescPregunta();
	}

	public function getEstadoImg()
	{
		if($this->getEstado() == 'ACT')
		{
			return "green.png";
		} elseif ($this->getEstado() == 'INA') {
			return "red.png";
		}
	}
}
