<?php

/**
 * EndpointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EndpointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EndpointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Endpoint');
    }
}