<?php

/**
 * FuncionPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncionPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncionPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuncionPais');
    }
}