<?php

/**
 * OportunidadCmr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OportunidadCmr extends BaseOportunidadCmr
{
	public function getFechaVigDesFormatted()
	{
		return $this->getFechaVigDes() != null ? date_format(date_create($this->getFechaVigDes()),'d-m-Y') : '';
		//return date_format(date_create($this->getFechaVigDes()),'d-m-Y');
	}
	public function getFechaVigHasFormatted()
	{
		return $this->getFechaVigHas() != null ? date_format(date_create($this->getFechaVigHas()),'d-m-Y') : '';
	}

// 	public function getNombreProductoFromSodimacCL()
// 	{
// 		$sodimac = new Sodimac(123456);
// 	}
}
