<?php

/**
 * Region
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sodimac
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Region extends BaseRegion
{
	public function __toString()
	{
		return $this->getDescRegion();
	}

  public function save(Doctrine_Connection $conn = null)
  {

      $endpoint = Doctrine_Core::getTable('Endpoint')->findOneByCodEndpoint('ZONAS');

      if($endpoint != null)
      {
        $endpoint->setVersion($endpoint->getVersion() + 1);
        $endpoint->save();
      }

    return parent::save($conn);
  }
  public function delete(Doctrine_Connection $conn = null)
  {

      $endpoint = Doctrine_Core::getTable('Endpoint')->findOneByCodEndpoint('ZONAS');

      if($endpoint != null)
      {
        $endpoint->setVersion($endpoint->getVersion() + 1);
        $endpoint->save();
      }

    return parent::delete($conn);
  }

}
