<?php

/**
 * ServiciosTiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiciosTiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiciosTiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiciosTienda');
    }

}