<?php

/**
 * ServiciosPorTiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiciosPorTiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiciosPorTiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiciosPorTienda');
    }
}