<?php

/**
 * TipoTiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTienda');
    }
}