<?php

/**
 * TipoPreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoPreguntaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoPreguntaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoPregunta');
    }
}