EncuestaCabeceraRespuestas:
  connection: doctrine
  tableName: encuesta_cabecera_respuestas
  columns:
    id_enc_cab_resp:  { type: integer(4),   fixed: false, unsigned: false, primary: true,  notnull: false, autoincrement: true }
    nro_boleta:       { type: string(100),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    fecha_compra:     { type: timestamp,    fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    id_tienda:        { type: integer,      fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    rut:              { type: integer(4),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    dv:               { type: string(1),    fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    nombre_completo:  { type: string(100),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    ciudad:           { type: string(50),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    telefono:         { type: string(12),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    celular:          { type: string(12),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    email:            { type: string(50),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    edad:             { type: integer(4),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    sexo:             { type: string(1),    fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    compra_para:      { type: string(100),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
  relations:
    EncuestaRespuestas: { local: id_enc_cab_resp, foreign: id_enc_cab_resp, type: many }

EncuestaPreguntas:
  connection: doctrine
  tableName: encuesta_preguntas
  columns:
    id_enc_preg:        { type: integer(4),   fixed: false, unsigned: false, primary: true,  notnull: false, autoincrement: true }
    id_tipo_preg:       { type: integer(4),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    valor_defecto:      { type: string(300),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    desc_pregunta:      { type: string(500),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    estado:             { type: string(3),    fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false, default: ACT }
    id_pais:            { type: integer(4),   fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
  relations:
    TipoPregunta:       { local: id_tipo_preg,  foreign: id_tipo_preg,  type: one }
    Pais:               { local: id_pais,       foreign: id_pais,       type: one }
    EncuestaRespuestas: { local: id_enc_preg,   foreign: id_enc_preg,   type: many }

EncuestaRespuestas:
  connection: doctrine
  tableName: encuesta_respuestas
  columns:
    id_enc_resp:      { type: integer(4), fixed: false, unsigned: false, primary: true, autoincrement: true }
    id_enc_preg:      { type: integer(4), fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    id_enc_cab_resp:  { type: integer(4), fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    valor_resp:       { type: string(300), fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
  relations:
    EncuestaPreguntas:          { local: id_enc_preg,     foreign: id_enc_preg,     type: one }
    EncuestaCabeceraRespuestas: { local: id_enc_cab_resp, foreign: id_enc_cab_resp, type: one, onDelete: CASCADE }

Endpoint:
  connection: doctrine
  tableName: endpoint
  columns:
    id_endpoint:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    cod_endpoint:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    desc_endpoint:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    host:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    puerto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    resto_url:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_pais:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pais:
      local: id_pais
      foreign: id_pais
      type: one
OportunidadCmr:
  connection: doctrine
  tableName: oportunidad_cmr
  columns:
    id_opor_cmr:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    sku:
      type: string(7)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nombre_producto:
      type: string(200)
      unsigned: false
      primary: false
      notnull: false 
      autoincrement: false
    precio_internet:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    unidad_med_int:
      type: string(10)
      unsigned: false
      primary: false
      notnull: false 
      autoincrement: false
    precio_cmr:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    unidad_med_cmr:
      type: string(10)
      unsigned: false
      primary: false
      notnull: false 
      autoincrement: false
    fecha_vig_des:
      type: timestamp
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_vig_has:
      type: timestamp
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_pais:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pais:
      local: id_pais
      foreign: id_pais
      type: one
Pais:
  connection: doctrine
  tableName: pais
  columns:
    id_pais:            { type: integer(4), fixed: false, unsigned: false, primary: true, autoincrement: false }
    desc_pais:          { type: string(20), fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    sigla:              { type: string(4),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    signo_moneda:       { type: string(5),  fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    con_decimal:        { type: boolean,    fixed: false, unsigned: false, primary: false, autoincrement: false, default: false }
  relations:
    EncuestaPreguntas:  { local: id_pais, foreign: id_pais, type: many }
    Endpoint:           { local: id_pais, foreign: id_pais, type: many }
    OportunidadCmr:     { local: id_pais, foreign: id_pais, type: many }
    Region:             { local: id_pais, foreign: id_pais, type: many }
    Tienda:             { local: id_pais, foreign: id_pais, type: many }

Region:
  connection: doctrine
  tableName: region
  columns:
    id:           { type: integer,    fixed: false, unsigned: false, primary: true,  autoincrement: true }
    id_region:    { type: integer(4), fixed: false, unsigned: false, primary: false, autoincrement: false, notnull: true }
    desc_region:  { type: string(60), fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
    id_pais:      { type: integer(4), fixed: false, unsigned: false, primary: false, notnull: true, autoincrement: false }
  relations:
    Pais:         { local: id_pais, foreign: id_pais, type: one }
  indexes:
    region_index:
      fields: [id_region,id_pais]
      primary: true
      type: unique

ServiciosPorTienda:
  connection: doctrine
  tableName: servicios_por_tienda
  columns:
    id_tienda: { type: integer, primary: true, notnull: true }
    id_servicio_tienda: { type: integer(4), fixed: false, unsigned: false, primary: true, autoincrement: false, notnull: true }
  relations:
    Tienda: { alias: tienda, local: id_tienda, foreign: id_tienda, onDelete: CASCADE }
    ServiciosTienda: { alias: servicios, local: id_servicio_tienda, foreign: id_servicio_tienda, onDelete: CASCADE }
  indexes:
    servicios_por_tienda_index:
      fields: [id_tienda,id_servicio_tienda]
      type: unique

ServiciosTienda:
  connection: doctrine
  tableName: servicios_tienda
  columns:
    id_servicio_tienda:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    desc_servicio:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estado:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ServiciosPorTienda:
      local: id_servicio_tienda
      foreign: id_servicio_tienda
      type: many
Tienda:
  connection: doctrine
  tableName: tienda
  columns:
    id_tienda:
      type: integer
      primary: true
      unique: true
      notnull: true
    nombre:
      type: string(70)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    direccion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    latitud:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    longitud:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefono:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    horario:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_region:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_tipo_tienda:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    id_pais:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    gerente:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    busc_producto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    TipoTienda:
      local: id_tipo_tienda
      foreign: id_tipo_tienda
      type: one
    Pais:
      local: id_pais
      foreign: id_pais
      type: one
    Region:
      local: id_region
      foreign: id
      onDelete: SET NULL
    ServiciosPorTienda:
      local: id_tienda
      foreign: id_tienda
      type: many
TipoPregunta:
  connection: doctrine
  tableName: tipo_pregunta
  columns:
    id_tipo_preg:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    desc_tipo_preg:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    EncuestaPreguntas:
      local: id_tipo_preg
      foreign: id_tipo_preg
      type: many

TipoTienda:
  connection: doctrine
  tableName: tipo_tienda
  columns:
    id_tipo_tienda:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    desc_tipo_tienda:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Tienda:
      local: id_tipo_tienda
      foreign: id_tipo_tienda
      type: many

Aplicacion:
  connection: doctrine
  tableName: aplicacion
  columns:
    id:           { type: integer,    fixed: false, unsigned: false, primary: true,  notnull: true, autoincrement: true }
    descripcion:  { type: string, fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }

AplicacionPais:
  connection: doctrine
  tableName: app_pais
  columns:
    id_aplicacion:  { type: integer, primary: true, notnull: true }
    id_pais:        { type: integer(4), primary: true, notnull: true }
  relations:
    Aplicacion:     { alias: aplicacion, local: id_aplicacion, foreign: id, onDelete: CASCADE }
    Pais:           { alias: pais, local: id_pais, foreign: id_pais, onDelete: CASCADE }
  indexes:
    app_pais_index:
      fields: [id_aplicacion,id_pais]
      type: unique

Funcion:
  connection: doctrine
  tableName: funcion
  columns:
    id:             { type: integer, primary: true, notnull: true, autoincrement: true }
    id_aplicacion:  { type: integer, primary: false, notnull: true }
    descripcion:    { type: string, fixed: false, unsigned: false, primary: false, notnull: false, autoincrement: false }
  relations:
    Aplicacion:     { local: id_aplicacion, foreign: id, type: one }

FuncionPais:
  connection: doctrine
  tableName: funcion_pais
  columns:
    id_funcion:   { type: integer, primary: true, notnull: true }
    id_pais:      { type: integer(4), primary: true, notnull: true }
  relations:
    Funcion:      { alias: funcion, local: id_funcion, foreign: id, onDelete: CASCADE }
    Pais:         { alias: pais, local: id_pais, foreign: id_pais, onDelete: CASCADE }
  indexes:
    funcion_pais_index:
      fields: [id_funcion,id_pais]
      type: unique
